# Generated by Django 2.0.4 on 2018-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20180929_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='body',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.CharField(default='XXXX', max_length=50),
        ),
    ]
